language = "rust"
type = "component"

[component]
wasm_target = "wasm32-wasip2"
# wasm_target = "wasm32-unknown-unknown"
build_command = "cargo +nightly build -Z unstable-options --release --target wasm32-wasip2 --artifact-dir build"
build_artifact = "build/python_component.wasm"
destination = "build/python_component_s.wasm"

[[registry.pull.sources]]
target = "thomas9911:expression@0.1.0"
source = "file://../../wit/expression.wit"
